apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-api
  template:
    metadata:
      labels:
        app: spring-api
    spec:
      containers:
        - name: spring-api
          image: arthuru0/arthuru0_devops:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: db-config
            - secretRef:
                name: db-secret
          livenessProbe:
            httpGet:
              path: /users/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /users/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 6
