version: "3.9"

services:
  api:
    image: devops
    container_name: spring-api
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres
      DB_USER: postgres.einaebrdojyexjjgsavr
      DB_PASS: sambamiudinho
    restart: always
